### ISSUE TITLE
Never output error in production

### ISSUE THREAD

**Issue by Cyl18** [Cyl18/CFPABot#3]
![image](https://user-images.githubusercontent.com/14993992/174159168-a42d2609-ef2d-428a-b965-6968b14e21f5.png)

**Comment by n0099** [comment]
never and ever

**Comment by Cyl18** [comment]
fixed in https://github.com/Cyl18/CFPABot/commit/4f56c3cca89bc933c39b91ee9501025ff75b7236#diff-66293245baa4edf306607ec943dae946a0fff12c4b644586060117a2d63a8d11R83-R87
