### ISSUE TITLE
/diff

### ISSUE THREAD

**Issue by Cyl18** [Cyl18/CFPABot#4]
/diff

_Originally posted by @mamaruo in https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2051#issuecomment-1166334745_

**Comment by Cyl18** [comment]
{"message":"Validation Failed","errors":[{"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}],"documentation_url":"https://docs.github.com/rest/reference/issues#create-an-issue-comment"}

**Comment by mamaruo** [comment]
能否拆成两个comment发

**Comment by Cyl18** [comment]
> 能否拆成两个comment发

~~我超这是没睡还是刚起~~

我打算传gist

**Comment by Cyl18** [comment]
https://gist.github.com/Cyl18-Bot/bfeeff940906efb812947d03e226987a
其实看着还是不太舒服 用GitHub还是。。
