### ISSUE TITLE
模组获取问题

### ISSUE THREAD

**Issue by Cyl18** [Cyl18/CFPABot#5]
- 经常不能获取到某个特定Minecraft版本的最新版
- 可能获取到alpha版本

**Comment by Ricky-fight** [comment]
获取到模组文件信息以后最好再对其按fileid降序排序，API有时候不是严格按照从新到旧的顺序返回的，应该可以解决无法获取到最新版的问题。另外还有forge端的模组文件却获取到fabric的模组文件里的语言文件的问题，这个可以过滤搜索条件解决

**Comment by Cyl18** [comment]
有问题我再打开
